services:
  # BACKEND SERVICE
  - type: web
    name: microfinance-backend
    runtime: node
    region: singapore # Optional, defaults to Oregon
    plan: free # Optional
    rootCommand: cd backend
    buildCommand: npm install && npx playwright install chromium
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/service_account.json

  # FRONTEND SERVICE
  - type: static
    name: microfinance-frontend
    region: singapore
    plan: free
    rootCommand: cd frontend
    buildCommand: npm install && npm run build
    publishDir: build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: microfinance-backend
          property: url
      - key: REACT_APP_FIREBASE_API_KEY
        sync: false
      - key: REACT_APP_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: REACT_APP_FIREBASE_PROJECT_ID
        sync: false
      - key: REACT_APP_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: REACT_APP_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: REACT_APP_FIREBASE_APP_ID
        sync: false
