services:
  # BACKEND SERVICE
  - type: web
    name: microfinance-backend
    runtime: node
    region: singapore # Optional, defaults to Oregon
    plan: free # Optional
    rootDir: backend
    buildCommand: npm install && npx playwright install chromium
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/service_account.json
